apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender
  labels:
    name: recommender
  namespace: sock-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      name: recommender
  template:
    metadata:
      labels:
        name: recommender
    spec:
      containers:
        - name: recommender
          image: kcz17/recommender:1.0.1
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
