apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiler
  labels:
    name: profiler
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: profiler
  template:
    metadata:
      labels:
        name: profiler
    spec:
      containers:
        - name: profiler
          image: kcz17/profiler:0.0.14
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          env:
            - name: CONNECTIONS_INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: profiler-influxdb
                  key: token
      volumes:
        - name: config-volume
          configMap:
            name: profiler-config
      nodeSelector:
        beta.kubernetes.io/os: linux
