apiVersion: v1
kind: Service
metadata:
  name: news-db
  labels:
    name: news-db
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
    - port: 3306
      targetPort: 3306
  selector:
    name: news-db
