apiVersion: v1
kind: Service
metadata:
  name: carts-reseeder
  labels:
    name: carts-reseeder
  namespace: sock-shop
spec:
  type: NodePort
  ports:
    - port: 81
      targetPort: 8079
      nodePort: 30004
  selector:
    name: carts-reseeder
