apiVersion: v1
kind: Service
metadata:
  name: profiler
  labels:
    name: profiler
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8080
  selector:
    name: profiler
