apiVersion: v1
kind: Service
metadata:
  name: profiler-db
  labels:
    name: profiler-db
  namespace: sock-shop
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: profiler-db
