apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
        - name: front-end
          image: kcz17/front-end:1.0.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8079
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
        - name: front-end-sidecar
          image: kcz17/http-sidecar:0.0.24
          ports:
            - containerPort: 8078
          env:
            - name: FE_PORT
              value: "8078"
            - name: BE_PORT
              value: "8079"
            - name: DIMMER_ENABLED
              value: "true"
            - name: NUM_REQUESTS_WINDOW
              value: "1000"
            - name: CONTROLLER_SAMPLE_PERIOD
              value: "1"
            - name: CONTROLLER_PERCENTILE
              value: "p95"
            - name: CONTROLLER_SETPOINT
              value: "7"
            - name: CONTROLLER_KP
              value: "0.5"
            - name: CONTROLLER_KI
              value: "0.5"
            - name: CONTROLLER_KD
              value: "0"
            - name: LOGGER_DRIVER
              value: "influxdb"
            - name: LOGGER_INFLUXDB_HOST
              value: "http://146.169.42.88:8086"
            - name: LOGGER_INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dimmer-influxdb
                  key: token
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: sock-shop
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8078
      nodePort: 30001
  selector:
    name: front-end
