apiVersion: v1
kind: Service
metadata:
  name: dimmer
  labels:
    name: dimmer
  namespace: sock-shop
spec:
  type: NodePort
  ports:
    - name: server
      port: 80
      targetPort: 8078
      nodePort: 30002
    - name: api
      port: 81
      targetPort: 8079
      nodePort: 30003
  selector:
    name: dimmer
