apiVersion: apps/v1
kind: Deployment
metadata:
  name: news
  labels:
    name: news
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: news
  template:
    metadata:
      labels:
        name: news
    spec:
      containers:
        - name: news
          image: kcz17/news:1.0.2
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
